<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows7.0</TargetFramework>
    <OutputType>WinExe</OutputType>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseWindowsForms>true</UseWindowsForms>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="ACE.Adapter, Version=1.0.0.0, Culture=neutral, processorArchitecture=MSIL">
      <SpecificVersion>False</SpecificVersion>
      <HintPath>lib\ACE.Adapter.dll</HintPath>
    </Reference>
    <Reference Include="ACE.Database, Version=1.0.0.0, Culture=neutral, processorArchitecture=MSIL">
      <SpecificVersion>False</SpecificVersion>
      <HintPath>lib\ACE.Database.dll</HintPath>
    </Reference>
    <Reference Include="ACE.Entity, Version=1.0.0.0, Culture=neutral, processorArchitecture=MSIL">
      <SpecificVersion>False</SpecificVersion>
      <HintPath>lib\ACE.Entity.dll</HintPath>
    </Reference>
    <Reference Include="Lifestoned.DataModel">
      <HintPath>lib\Lifestoned.DataModel.dll</HintPath>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <Compile Update="ParserControl.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="SQLBuilderControl.cs">
      <SubType>UserControl</SubType>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="log4net">
      <Version>2.0.17</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <Version>8.0.20</Version>
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="MySql.Data" Version="8.4.0" />
    <PackageReference Include="Newtonsoft.Json">
      <Version>13.0.4</Version>
    </PackageReference>
    <PackageReference Include="Pomelo.EntityFrameworkCore.MySql">
      <Version>8.0.3</Version>
    </PackageReference>
  </ItemGroup>
    <Target Name="ChangeAliasesOfStrongNameAssemblies" BeforeTargets="FindReferenceAssembliesForReferences;ResolveReferences">
        <ItemGroup>
            <ReferencePath Condition="'%(FileName)' == 'MySqlConnector'">
                <Aliases>MySqlConnectorAlias</Aliases>
            </ReferencePath>
        </ItemGroup>
    </Target>
</Project>